"""Write H05 goal-period folders (G<NN>/README.md) from the exploratory round-1 outputs.

Round 1 ran per window but reported pooled; this retrofit lays the per-period numbers out in the
project's goal-period folders. No period-specific predictions were written before round 1, so each
folder is scored against the card's P2 as it applies to that period.

A folder whose README lacks the GENERATED marker has been hand-edited and is left alone.
Usage: uv run python hypotheses/H05-rooms-cut/analysis/write_period_folders.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import polars as pl

ROOT = Path(__file__).resolve().parents[3]
H = ROOT / "hypotheses/H05-rooms-cut"
D = ROOT / "data/processed/H05-rooms-cut"
sys.path.insert(0, str(ROOT / "infra/ai_village_overview"))
from figures import GOAL_SHORT  # noqa: E402

MARK = "<!-- GENERATED by analysis/write_period_folders.py (round-1 retrofit) -->"
P2_WINDOWS = {37, 38, 39, 41, 42, 44}  # regime-III two-room windows named in P2


def f(x, nd=3):
    return "—" if x is None else f"{x:+.{nd}f}"


def verdict(k):
    """P2 for talk kappa_x: within/cross >= 1.5 (or cross <= 0 < within) and room-label permutation p < 0.05."""
    w, c, p = k["within"], k["cross"], k["p_perm"]
    ratio_ok = (c <= 0 < w) or (c > 0 and w / c >= 1.5)
    if w <= c:
        return "failed"
    return "supported" if ratio_ok and p < 0.05 else "mixed"


def main():
    b1 = json.load(open(D / "explore_bin1.json"))["X2"]
    b5 = json.load(open(D / "explore_bin5.json"))["X2"]
    mf = json.load(open(D / "mf_blocks.json"))["MF1"]["talk"]
    cal = (pl.read_parquet(ROOT / "data/processed/shared/calendar.parquet").group_by("goal_no")
           .agg(pl.col("pt_date").min().alias("s"), pl.col("pt_date").max().alias("e"), pl.col("regime").first().cast(pl.String)))
    cal = {r["goal_no"]: r for r in cal.iter_rows(named=True)}
    rows = []
    for g in sorted(int(k) for k in b1["talk"]):
        t, a, t5 = b1["talk"][str(g)], b1["active"].get(str(g), {}), b5["talk"].get(str(g), {})
        m = mf.get(str(g), {})
        c = cal[g]
        in_p2 = g in P2_WINDOWS
        v = verdict(t["kappa_x"]) if in_p2 else "descriptive"
        folder = H / "goalperiod-subhypotheses" / f"G{g:02d}"
        readme = folder / "README.md"
        if readme.exists() and MARK not in readme.read_text():
            print("skip (hand-edited)", folder.name); continue
        folder.mkdir(exist_ok=True)
        rooms = ", ".join(f"room {k}: {n}" for k, n in t["rooms"].items())
        kx, k5 = t["kappa_x"], t5.get("kappa_x", {})
        txt = f"""# H05 × G{g:02d}: {GOAL_SHORT.get(g, '').replace('\\#', '#').split('(Table')[0].strip()} ({c['s']} → {c['e']})
{MARK}

**Verdict:** {v}{'' if in_p2 else ' (not one of the P2 two-room windows; numbers reported for context)'}
**Role:** exploratory (round 1, non-holdout)
**Period:** regime {c['regime']} · {t['n_agents']} agents · {t['days']} days · {rooms} · {t['n_within']} within-room pairs, {t['n_cross']} cross-room pairs.

## Prediction
No period-specific prediction was written before round 1 (it ran over all windows at once). The card's **P2** applies{' to this period' if in_p2 else ' only to the regime-III two-room windows #37–#39, #41, #42, #44, so this period is descriptive'}: within-room pairs couple more than cross-room pairs, excess κ within/cross ≥ 1.5, and the room partition beats random partitions (p < 0.05). Talk spins are the primary channel.
Verdict rule applied here: **supported** if both hold for talk κ_x; **mixed** if within > cross but not both; **failed** if within ≤ cross.

## Result (talk spins unless stated; excess over the cross-day surrogate)
| Measure | Within | Cross | Diff | Room-label p | Null SD |
| --- | --- | --- | --- | --- | --- |
| κ_x, 1-min (primary) | {f(kx['within'], 4)} | {f(kx['cross'], 4)} | {f(kx['diff'], 4)} | {kx['p_perm']:.3f} | {kx['null_sd']:.4f} |
| κ_x, 5-min | {f(k5.get('within'), 4)} | {f(k5.get('cross'), 4)} | {f(k5.get('diff'), 4)} | {k5.get('p_perm', float('nan')):.3f} | {k5.get('null_sd', float('nan')):.4f} |
| c0_x, 1-min | {f(t['c0_x']['within'], 4)} | {f(t['c0_x']['cross'], 4)} | {f(t['c0_x']['diff'], 4)} | {t['c0_x']['p_perm']:.3f} | {t['c0_x']['null_sd']:.4f} |
| J_sym (kinetic Ising) | {f(t['J_sym']['within'], 4)} | {f(t['J_sym']['cross'], 4)} | {f(t['J_sym']['diff'], 4)} | {t['J_sym']['p_perm']:.3f} | |
| κ_x, active spins | {f(a.get('kappa_x', {}).get('within'), 4)} | {f(a.get('kappa_x', {}).get('cross'), 4)} | {f(a.get('kappa_x', {}).get('diff'), 4)} | {a.get('kappa_x', {}).get('p_perm', float('nan')):.3f} | |
"""
        if m:
            txt += f"""
**Two-block mean field (H05-MF, talk):** J_in = {m['J_in']:+.3f} [{m['J_in_ci95'][0]:+.3f}, {m['J_in_ci95'][1]:+.3f}], J_out = {m['J_out']:+.3f} [{m['J_out_ci95'][0]:+.3f}, {m['J_out_ci95'][1]:+.3f}], p(J_in > J_out) = {m['p_perm_in_gt_out']:.3f}, loop gain {m['loop_gain']:.3f} ({m['n_agents']} agents in the two largest rooms).
"""
        txt += f"""
Source: `data/processed/H05-rooms-cut/explore_bin1.json`, `explore_bin5.json` (X2), `mf_blocks.json` (MF1); code `analysis/explore_rooms.py`, `analysis/mf_blocks.py`.

## Notes
- Per-period inference has low power (H05 V4: 23–63% for a full cut at village coupling); the card's pooled tests carry the weight.
"""
        if g == 35:
            txt += "- #35 is the post-split half of the NE15 test. Its numbers were seen in round 1, before the confirmatory run; only the pre-split baseline (#33–#34) was held out. See [../NE15/README.md](../NE15/README.md).\n"
        readme.write_text(txt)
        rows.append((g, v, kx["diff"], kx["p_perm"]))
        print(f"G{g:02d}", v, f"{kx['diff']:+.4f}", f"p={kx['p_perm']:.3f}")


if __name__ == "__main__":
    main()
