"""Write writeup/paper/sections/compendium.tex: the hypothesis compendium as the paper's last appendix.

    uv run python writeup/paper/make_compendium_tex.py

Every card's two-page summary (hypotheses/H*/summary/summary.pdf, built by infra/summaries/build_summaries.py) is
included with pdfpages, in card order, each with a PDF bookmark and a label; an index of all cards with page links
opens the appendix. Rebuild the summaries first if cards changed.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HYP = ROOT / "hypotheses"
OUT = ROOT / "writeup/paper/sections/compendium.tex"


def tex(s: str) -> str:
    s = re.sub(r"\$[^$]*\$", lambda m: m.group(0), s)
    out = []
    for part in re.split(r"(\$[^$]*\$)", s):
        if part.startswith("$"):
            out.append(part); continue
        for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("#", r"\#"), ("_", r"\_"),
                     ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")):
            part = part.replace(a, b)
        for a, b in (("²", r"$^2$"), ("ó", r"\'o"), ("β", r"$\beta$"), ("κ", r"$\kappa$"), ("χ", r"$\chi$"),
                     ("–", "--"), ("−", r"$-$"), ("≈", r"$\approx$")):
            part = part.replace(a, b)
        out.append(part)
    return "".join(out)


def main():
    cards = []
    for d in sorted((p for p in HYP.iterdir() if re.match(r"^H\d{2,}-", p.name)), key=lambda p: int(p.name[1:].split("-")[0])):
        pdf = d / "summary/summary.pdf"
        if not pdf.exists():
            continue
        first = (d / "README.md").read_text(errors="replace").splitlines()[0]
        title = first.lstrip("# ").strip()
        title = re.sub(r"^H\d+\s*[—–:-]\s*", "", title)
        title = title.replace("holdout", "reserved").replace("Holdout", "Reserved")
        cards.append(dict(id=d.name.split("-")[0], title=title, pdf=Path("../../hypotheses") / d.name / "summary/summary.pdf"))
    L = ["% Generated by writeup/paper/make_compendium_tex.py; do not edit by hand.",
         r"\clearpage",
         r"\section{Hypothesis compendium}\label{app:compendium}",
         rf"The following {2 * len(cards)} pages give every hypothesis card ({len(cards)} in all) as its two-page summary, "
         r"in card order: the question, the physics model and data scheme, the dated prediction and null, the result in each goal "
         r"period it was tested on, the scorecard, and the claim that was scored (Sec.~\ref{sec:faith}). The summaries are "
         r"generated from the cards by \texttt{infra/summaries/build\_summaries.py}. Cards H133--H142 ran on 2026-10-07 and are "
         r"not yet scored. Click an entry to jump to its pages.",
         r"\par\medskip",
         r"\twocolumngrid", r"{\footnotesize\raggedright"]
    for c in cards:
        L.append(rf"\noindent\hyperref[cmp:{c['id']}]{{\textbf{{{c['id']}}}~{tex(c['title'])}}}\dotfill\pageref{{cmp:{c['id']}}}\par")
    L += [r"}", r"\onecolumngrid", r"\clearpage"]
    # one full page per summary page, drawn as a background picture; bookmark and label on each card's first page
    L.append(r"\newcommand{\cmppage}[3]{\clearpage\thispagestyle{empty}"
             r"\AddToShipoutPictureBG*{\put(0,0){\includegraphics[page=#2,width=\paperwidth,height=\paperheight]{#1}}}"
             r"\mbox{}#3\clearpage}")
    for c in cards:
        f = c["pdf"].as_posix()
        mark = rf"\phantomsection\label{{cmp:{c['id']}}}\pdfbookmark[2]{{{c['id']}: {tex(c['title'])}}}{{bm:{c['id']}}}"
        L.append(rf"\cmppage{{{f}}}{{1}}{{{mark}}}")
        L.append(rf"\cmppage{{{f}}}{{2}}{{}}")
    OUT.write_text("\n".join(L) + "\n")
    print(f"{len(cards)} cards -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
