"""Write H02 goal-period folders (G<NN>/README.md) from the exploratory round-1 outputs.

Round 1 fitted each goal period in chunks of up to 5 days and reported pooled; this retrofit lays the
per-period numbers out in goal-period folders. No period-specific predictions were written before round 1,
so each folder is scored against the card's RP1 (pairwise) as it applies to that period's mode:
  mode I: 8-20% significant couplings (block fit vs N1); mode C: >= 1.5 x 8% = 12%.
The calibrated false-positive rate of that test is 5.8-7.6%. Mean-field (CW) numbers are reported alongside.

A folder whose README lacks the GENERATED marker has been hand-edited and is left alone.
Usage: uv run python hypotheses/H02-couplings-are-real/analysis/write_period_folders.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import polars as pl

ROOT = Path(__file__).resolve().parents[3]
H = ROOT / "hypotheses/H02-couplings-are-real"
D = ROOT / "data/processed/H02-couplings-are-real"
sys.path.insert(0, str(ROOT / "infra/ai_village_overview"))
from figures import GOAL_SHORT  # noqa: E402

MARK = "<!-- GENERATED by analysis/write_period_folders.py (round-1 retrofit) -->"
THRESH = {"I": 0.08, "C": 0.12}


def main():
    ch = pl.read_parquet(D / "real_chunks.parquet")
    cw = pl.read_parquet(D / "mf_cw.parquet").select("chunk", "bJ0", "z", "p", "tvd_ind", "tvd_cw")
    nl = pl.read_parquet(D / "mf_cw_nolull.parquet").select("chunk", "bJ0_nolull", "z_nolull", "drop_frac")
    ch = ch.join(cw, on="chunk", how="left").join(nl, on="chunk", how="left")
    cal = (pl.read_parquet(ROOT / "data/processed/shared/calendar.parquet").group_by("goal_no")
           .agg(pl.col("pt_date").min().alias("s"), pl.col("pt_date").max().alias("e")))
    cal = {r["goal_no"]: r for r in cal.iter_rows(named=True)}
    for g, sub in sorted(ch.group_by("goal_no"), key=lambda kv: kv[0][0]):
        g = int(g[0]); sub = sub.sort("chunk")
        mode, regime = sub["mode"][0], sub["regime"][0]
        thr = THRESH[mode]
        fs = sub["block_N1_frac_sig"].to_list()
        if all(x >= thr for x in fs):
            v = "supported"
        elif any(x >= thr for x in fs):
            v = "mixed"
        else:
            v = "failed"
        folder = H / "goalperiod-subhypotheses" / f"G{g:02d}"; readme = folder / "README.md"
        if readme.exists() and MARK not in readme.read_text():
            print("skip (hand-edited)", folder.name); continue
        folder.mkdir(exist_ok=True)
        rows = "\n".join(
            f"| {r['chunk']} | {r['N']} | {r['n_days']} | {r['act']:.2f} | **{r['block_N1_frac_sig']:.3f}** | {r['naive_N0_frac_sig']:.3f} | "
            f"{r['ho_days_M3_gt_M1']}/{r['n_days']} | {r['bJ0']:.3f} (z {r['z']:.1f}) | "
            + (f"{r['bJ0_nolull']:.3f} (z {r['z_nolull']:.1f})" if r["bJ0_nolull"] is not None else "—") + " |"
            for r in sub.iter_rows(named=True))
        c = cal[g]
        txt = f"""# H02 × G{g:02d}: {GOAL_SHORT.get(g, '').replace('\\#', '#').split('(Table')[0].strip()} ({c['s']} → {c['e']})
{MARK}

**Verdict:** {v}
**Role:** exploratory (round 1, non-holdout)
**Period:** regime {regime} · mode {mode} ({'shared objective' if mode == 'C' else 'individual objectives'}) · {sub['N'].max()} agents · {sub['n_days'].sum()} days in {sub.height} chunk(s) of ≤ 5 days.

## Prediction
No period-specific prediction was written before round 1 (it ran over all chunks at once). The card's **RP1** applies: the fraction of significant pairwise couplings (KI-1 + block fields vs the N1 surrogate) is **{'8–20%' if mode == 'I' else '≥ 12% (1.5 × the mode-I level)'}** in a mode-{mode} week. The test's calibrated false-positive rate is 5.8–7.6%, so values in that range mean "at the null floor".
Verdict rule applied here: **supported** if every chunk reaches the threshold ({thr:.0%}); **mixed** if some do; **failed** if none do.

## Result
| Chunk | N | Days | Activity | Frac. sig. (block vs N1) | Frac. sig. (naive vs N0) | Held-out days pairwise > indep. | CW βJ₀ (z) | CW βJ₀ without joint lulls (z) |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
{rows}

Mean-field reading (H02-MF): βJ₀ with z ≥ 2 after removing joint-silence bins means collective co-activation survives; far below criticality throughout (βJ₀·q ≤ 0.36 in round 1).
Source: `data/processed/H02-couplings-are-real/real_chunks.parquet`, `mf_cw.parquet`, `mf_cw_nolull.parquet`; code `analysis/nulls_real.py`, `analysis/heldout_null.py`, `analysis/mf.py`.

## Notes
"""
        if g == 26:
            txt += "- #26 (election): the elected leader (agent 17) ranks 8/10 by net outgoing influence (z = −0.70); weak ground truth, since the leader only picked the goal (`dryrun_g26.json`).\n"
        readme.write_text(txt)
        print(f"G{g:02d}", mode, v, [round(x, 3) for x in fs])


if __name__ == "__main__":
    main()
