"""Build hypotheses/OVERVIEW.md: the goal-period x hypothesis table of verdicts.

Scans hypotheses/H*/goalperiod-subhypotheses/{G<NN>[a-z],NE<NN>}/README.md for their
`**Verdict:**` and `**Role:**` lines. Never edit OVERVIEW.md by hand; rerun this instead.

Usage: uv run python infra/overview/build_overview.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import polars as pl

ROOT = Path(__file__).resolve().parents[2]
HYP = ROOT / "hypotheses"
sys.path.insert(0, str(ROOT / "infra/ai_village_overview"))
from figures import GOAL_SHORT  # noqa: E402

PERIOD_RE = re.compile(r"^(G(\d{2})([a-z]?)|NE(\d{2}))$")
SYMBOL = {"supported": "✓", "failed": "✗", "mixed": "~", "descriptive": "d", "pending": "…", "n/a": "–"}


def field(text: str, name: str) -> str:
    m = re.search(rf"^\*\*{name}:\*\*\s*(.+)$", text, re.M)
    return m.group(1).strip() if m else ""


def verdict_symbol(v: str) -> str:
    sys.path.insert(0, str(ROOT / "dashboard"))
    from collect import verdict_key  # one parser for verdicts everywhere
    return SYMBOL.get(verdict_key(v), "?")


def main():
    hyps = sorted(d for d in HYP.iterdir() if d.is_dir() and re.match(r"^H\d{2}-", d.name))
    cells, periods = {}, set()
    for h in hyps:
        sub = h / "goalperiod-subhypotheses"
        cands = (list(sub.iterdir()) if sub.is_dir() else []) + [d for d in h.iterdir() if not (sub / d.name).exists()]
        for d in cands:
            if d.is_dir() and PERIOD_RE.match(d.name) and (d / "README.md").exists():
                t = (d / "README.md").read_text()
                v, role = field(t, "Verdict"), field(t, "Role")
                sym = verdict_symbol(v)
                if role.lower().startswith("confirm"):
                    sym = f"**{sym}**"
                cells[(d.name, h.name)] = f"[{sym}]({d.relative_to(HYP).as_posix()}/README.md)"
                periods.add(d.name)

    cal = None
    cal_path = ROOT / "data/processed/shared/calendar.parquet"
    if cal_path.exists():
        cal = (pl.read_parquet(cal_path).group_by("goal_no")
               .agg(pl.col("pt_date").min().alias("start"), pl.col("pt_date").max().alias("end"),
                    pl.col("regime").first().cast(pl.String), pl.col("holdout").any()))
        cal = {r["goal_no"]: r for r in cal.iter_rows(named=True)}

    def key(p):
        m = PERIOD_RE.match(p)
        return (0, int(m.group(2)), m.group(3)) if m.group(2) else (1, int(m.group(4)), "")

    short = [h.name.split("-")[0] for h in hyps]
    lines = ["# Overview: hypotheses × goal periods", "",
             "*Generated by `infra/overview/build_overview.py` from the `G<NN>/` and `NE<NN>/` folders. Do not edit by hand.*", "",
             "Legend: ✓ supported · ✗ failed · ~ mixed · d descriptive · … pending · – n/a · **bold** = confirmatory (locked holdout) · 🔒 = held-out period.", "",
             "| Period | Goal | Regime | Dates | " + " | ".join(short) + " |",
             "| --- | --- | --- | --- | " + " | ".join("---" for _ in short) + " |"]
    for p in sorted(periods, key=key):
        m = PERIOD_RE.match(p)
        if m.group(2):
            g = int(m.group(2)); c = (cal or {}).get(g)
            title = GOAL_SHORT.get(g, "").replace("~", " ").replace("\\#", "#").split("(Table")[0].strip()
            lock = " 🔒" if c and c["holdout"] else ""
            meta = [f"{title}{lock}", c["regime"] if c else "", f"{c['start']} → {c['end']}" if c else ""]
        else:
            meta = ["natural experiment (spans periods)", "", "see `hypotheses/natural-experiments.md`"]
        lines.append(f"| {p} | " + " | ".join(meta) + " | " + " | ".join(cells.get((p, h.name), "") for h in hyps) + " |")
    lines += ["", "## Per hypothesis", ""]
    for h in hyps:
        mine = sorted((p for (p, hn) in cells if hn == h.name), key=key)
        lines.append(f"- **[{h.name}]({h.name}/README.md)**: {len(mine)} period folder(s)" + (f": {', '.join(mine)}" if mine else ""))
    (HYP / "OVERVIEW.md").write_text("\n".join(lines) + "\n")
    print(f"{len(periods)} periods, {len(cells)} entries → hypotheses/OVERVIEW.md")


if __name__ == "__main__":
    main()
